apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: firm-owl-go 
  janus-idp.io/tekton: firm-owl-go
  backstage.io/kubernetes-id: firm-owl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: firm-owl-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  